#debug: true

server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.eshaon.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
      name: provider-dept  #8001/8002/8003对外暴露的服务实例名要一样
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
      url: jdbc:mysql://localhost:3306/cloudDB03              # 数据库名称
      username: root
      password: root
      dbcp2:
          min-idle: 5                                           # 数据库连接池的最小维持连接数
          initial-size: 5                                       # 初始化连接数
          max-total: 5                                          # 最大连接数
          max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端provider注册到eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept8003  #自定义服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: eshaon-microservicecloud
  company.name: www.eshaon.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}






