server:
  port: 80


#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

spring:
  application:
      name: consumer-dept

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: consumer-dept80
    prefer-ip-address: true     #访问路径可以显示IP地址
